# Generated by Django 4.2.30 on 2026-04-30 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_taskcompletion_alter_task_learning_outcomes_and_more'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-completion_date'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='average_score',
            field=models.FloatField(default=0.0, help_text='Average score across all portfolio items'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Portfolio summary/bio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether portfolio is publicly viewable'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Portfolio title', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_items',
            field=models.IntegerField(default=0, help_text='Count of completed portfolio items'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When task was completed', null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order to display items in portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='evaluation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When evaluation was completed', null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='final_score',
            field=models.FloatField(default=0.0, help_text='Final combined score'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether to feature this item prominently'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='mcq_score',
            field=models.FloatField(default=0.0, help_text='MCQ quiz score'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='mentor_feedback_summary',
            field=models.TextField(blank=True, default='', help_text='Key points from mentor feedback'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='mentor_score',
            field=models.FloatField(blank=True, help_text='Mentor evaluation score', null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_summary',
            field=models.TextField(blank=True, default='', help_text='Concise professional summary of the project'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='skills_demonstrated',
            field=models.JSONField(default=list, help_text='List of skills demonstrated in this task'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='strengths_summary',
            field=models.TextField(blank=True, default='', help_text='Strengths demonstrated (bullet list)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='student_reflection',
            field=models.TextField(blank=True, default='', help_text="Student's reflection on the task"),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='task_difficulty',
            field=models.CharField(blank=True, default='', help_text='Task difficulty level', max_length=15),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='task_domain',
            field=models.CharField(blank=True, default='', help_text='Task domain', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='task_evaluation',
            field=models.OneToOneField(blank=True, help_text='The evaluation this item is based on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_item', to='tasks.taskevaluation'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='task_title',
            field=models.CharField(blank=True, default='', help_text='Task title', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='task_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(help_text='Student who owns this portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Concise professional summary of the project'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolios.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task this item is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
