# Generated by Django 5.0.7 on 2026-05-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=True),
        ),
    ]
