# Generated by Django 4.2.11 on 2026-02-25 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Content Writing', 'Content Writing'), ('Programming', 'Programming'), ('Freelancing', 'Freelancing'), ('E-Commerce', 'E-Commerce'), ('QuickBooks', 'QuickBooks'), ('AutoCAD', 'AutoCAD'), ('Data Analytics', 'Data Analytics'), ('Digital Marketing', 'Digital Marketing'), ('WordPress', 'WordPress')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['domain', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='Dict mapping question_id -> selected_option (A/B/C/D)')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=15)),
                ('recommended_domains', models.JSONField(default=list, help_text='List of recommended domain/career objects')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
