# Generated by Django 5.0.7 on 2026-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_concept_attempt_rich_eval'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='feedback',
            field=models.JSONField(blank=True, default=dict, help_text='Structured feedback dict: {summary, strength, weakness, recommendation, suggested_task_type, tone, cluster_insight, mentor_insight, full_text}'),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='improvement_delta',
            field=models.FloatField(blank=True, help_text='Percentage-point change from previous attempt in this domain (null = first attempt)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='concept',
            field=models.CharField(blank=True, default='', help_text='Concept or sub-topic this question tests (e.g. "loops", "typography")', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_weight',
            field=models.FloatField(default=1.0, help_text='Scoring weight relative to other questions in the same assessment'),
        ),
    ]
