# Generated by Django 4.2.30 on 2026-04-30 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reflective_text', models.TextField(blank=True, default='', help_text="Student's reflection on what they learned")),
                ('is_submitted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='learning_outcomes',
            field=models.JSONField(default=list, help_text='What student will learn (e.g., ["Master typography", "Design logos"])'),
        ),
        migrations.AlterField(
            model_name='task',
            name='required_skills',
            field=models.JSONField(default=list, help_text='List of skills needed (e.g., ["Illustrator", "Color Theory"])'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='mentor_feedback',
            field=models.TextField(blank=True, default='', help_text="Mentor's review feedback"),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='recommendation_reason',
            field=models.TextField(blank=True, default='', help_text='Why this task was recommended to the student'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='recommended_score',
            field=models.FloatField(default=0.0, help_text='Score 0-100 indicating how well matched this task is'),
        ),
        migrations.CreateModel(
            name='TaskMCQAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answers', models.JSONField(default=dict, help_text='Student\'s MCQ answers: {question_id: "answer_choice"}')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('mcq_score', models.FloatField(default=0.0, help_text='Score calculated from MCQ: 0-100')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Time taken to complete quiz in seconds')),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_completion', models.OneToOneField(help_text='The task completion this MCQ attempt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempt', to='tasks.taskcompletion')),
            ],
            options={
                'db_table': 'task_mcq_attempts',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The MCQ question')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation for the correct answer')),
                ('order', models.IntegerField(default=0, help_text='Question order within the quiz')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='Task this MCQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='tasks.task')),
            ],
            options={
                'db_table': 'task_mcq_questions',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_score', models.FloatField(default=0.0, help_text='Score from MCQ: 0-100')),
                ('mentor_score', models.FloatField(blank=True, help_text='Manual score from mentor: 0-100 (null if not yet evaluated)', null=True)),
                ('final_score', models.FloatField(default=0.0, help_text='Final combined score: 0-100 (avg of MCQ + mentor, or MCQ if no mentor)')),
                ('mentor_feedback', models.TextField(blank=True, default='', help_text='Detailed feedback from mentor')),
                ('strengths', models.JSONField(default=list, help_text="List of student's strengths demonstrated in task")),
                ('weaknesses', models.JSONField(default=list, help_text='List of areas for improvement')),
                ('suggestions', models.JSONField(default=list, help_text='List of suggestions for improvement')),
                ('status', models.CharField(choices=[('pending', 'Pending Evaluation'), ('evaluated', 'Evaluated'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='When mentor completed the evaluation', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, help_text='Mentor who evaluated this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('task_completion', models.OneToOneField(help_text='The task completion being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tasks.taskcompletion')),
            ],
            options={
                'db_table': 'task_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='task_assignment',
            field=models.OneToOneField(help_text='The task assignment being completed', on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='tasks.taskassignment'),
        ),
    ]
