# Generated by Django 5.0.7 on 2026-05-06 01:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_taskassignment_recommendation_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('text', 'Text / Essay'), ('file', 'File Upload')], default='text', max_length=10)),
                ('text_content', models.TextField(blank=True, help_text='Written work submitted by the student for AI evaluation.')),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.taskassignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_evaluation', to='submissions.submission')),
            ],
            options={
                'db_table': 'mentor_evaluations',
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField(default=0.0, help_text='Overall AI score 0-100')),
                ('readability_score', models.FloatField(default=0.0)),
                ('vocabulary_diversity', models.FloatField(default=0.0)),
                ('grammar_score', models.FloatField(default=0.0)),
                ('originality_score', models.FloatField(default=100.0, help_text='100 = fully original, lower = similarity detected')),
                ('word_count', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('readiness_label', models.CharField(choices=[('Needs Work', 'Needs Work'), ('Satisfactory', 'Satisfactory'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Needs Work', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('grammar_issues', models.JSONField(default=list)),
                ('plagiarism_score', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='submissions.submission')),
            ],
            options={
                'db_table': 'ai_evaluations',
            },
        ),
    ]
