"""
Management command: seed_assessments
Creates sample assessments and MCQ questions for the prototype.

Usage:
    python manage.py seed_assessments
    python manage.py seed_assessments --clear   (removes existing then re-seeds)
"""

from django.core.management.base import BaseCommand
from apps.assessments.models import Assessment, Question


SEED_DATA = [
    {
        'title': 'Web Development Fundamentals',
        'domain': 'Programming',
        'description': 'Test your knowledge of HTML, CSS, JavaScript, and web development concepts.',
        'time_limit': 15,
        'questions': [
            {
                'text': 'What does HTML stand for?',
                'option_a': 'Hyper Text Markup Language',
                'option_b': 'High Tech Modern Language',
                'option_c': 'Hyper Transfer Markup Language',
                'option_d': 'Home Tool Markup Language',
                'correct_option': 'A',
            },
            {
                'text': 'Which CSS property is used to change the text color?',
                'option_a': 'font-color',
                'option_b': 'text-color',
                'option_c': 'color',
                'option_d': 'text-style',
                'correct_option': 'C',
            },
            {
                'text': 'Which of the following is a JavaScript framework?',
                'option_a': 'Django',
                'option_b': 'React',
                'option_c': 'Laravel',
                'option_d': 'Flask',
                'correct_option': 'B',
            },
            {
                'text': 'What does CSS stand for?',
                'option_a': 'Computer Style Sheets',
                'option_b': 'Creative Style System',
                'option_c': 'Cascading Style Sheets',
                'option_d': 'Colorful Style Sheets',
                'correct_option': 'C',
            },
            {
                'text': 'Which HTML tag is used for the largest heading?',
                'option_a': '<heading>',
                'option_b': '<h6>',
                'option_c': '<head>',
                'option_d': '<h1>',
                'correct_option': 'D',
            },
            {
                'text': 'What is the correct syntax for referring to an external script called "app.js"?',
                'option_a': '<script href="app.js">',
                'option_b': '<script name="app.js">',
                'option_c': '<script src="app.js">',
                'option_d': '<script file="app.js">',
                'correct_option': 'C',
            },
            {
                'text': 'Which operator is used for strict equality in JavaScript?',
                'option_a': '==',
                'option_b': '===',
                'option_c': '!=',
                'option_d': '=',
                'correct_option': 'B',
            },
            {
                'text': 'What does the "box model" in CSS consist of?',
                'option_a': 'Content, Padding, Border, Margin',
                'option_b': 'Header, Body, Footer, Sidebar',
                'option_c': 'Width, Height, Color, Font',
                'option_d': 'Display, Position, Float, Clear',
                'correct_option': 'A',
            },
            {
                'text': 'Which method is used to add an element at the end of an array in JavaScript?',
                'option_a': 'append()',
                'option_b': 'push()',
                'option_c': 'add()',
                'option_d': 'insert()',
                'correct_option': 'B',
            },
            {
                'text': 'What does REST stand for in web APIs?',
                'option_a': 'Representational State Transfer',
                'option_b': 'Remote Execution Standard Technology',
                'option_c': 'Rapid Enterprise Service Toolkit',
                'option_d': 'Resource State Transformation',
                'correct_option': 'A',
            },
            {
                'text': 'Which HTTP method is used to update an existing resource?',
                'option_a': 'GET',
                'option_b': 'POST',
                'option_c': 'PUT',
                'option_d': 'DELETE',
                'correct_option': 'C',
            },
            {
                'text': 'What is the purpose of the "alt" attribute in an <img> tag?',
                'option_a': 'To provide a link to another image',
                'option_b': 'To specify alternative text for the image',
                'option_c': 'To set the image alignment',
                'option_d': 'To define the image size',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'Content Writing Skills Assessment',
        'domain': 'Content Writing',
        'description': 'Evaluate your content writing, grammar, SEO, and copywriting knowledge.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'What does SEO stand for?',
                'option_a': 'Search Engine Optimization',
                'option_b': 'Social Engagement Outreach',
                'option_c': 'Search Entry Operation',
                'option_d': 'Site Enhancement Organization',
                'correct_option': 'A',
            },
            {
                'text': 'Which of the following is the ideal length for a meta description?',
                'option_a': '50–60 characters',
                'option_b': '150–160 characters',
                'option_c': '250–300 characters',
                'option_d': '500+ characters',
                'correct_option': 'B',
            },
            {
                'text': 'What is "CTA" in content writing?',
                'option_a': 'Central Text Alignment',
                'option_b': 'Call To Action',
                'option_c': 'Content Tracking Analytics',
                'option_d': 'Creative Text Arrangement',
                'correct_option': 'B',
            },
            {
                'text': 'Which sentence is grammatically correct?',
                'option_a': 'Their going to the store.',
                'option_b': 'There going to the store.',
                'option_c': 'They\'re going to the store.',
                'option_d': 'Theyre going to the store.',
                'correct_option': 'C',
            },
            {
                'text': 'What is a "hook" in content writing?',
                'option_a': 'A paragraph at the end of an article',
                'option_b': 'An attention-grabbing opening sentence',
                'option_c': 'A citation from another source',
                'option_d': 'A keyword repeated throughout the text',
                'correct_option': 'B',
            },
            {
                'text': 'Which tool is commonly used for checking plagiarism?',
                'option_a': 'Photoshop',
                'option_b': 'Turnitin',
                'option_c': 'Slack',
                'option_d': 'Trello',
                'correct_option': 'B',
            },
            {
                'text': 'What is keyword density?',
                'option_a': 'The total number of words in a document',
                'option_b': 'The percentage of times a keyword appears relative to total word count',
                'option_c': 'The font weight of keywords in an article',
                'option_d': 'The spacing between keywords',
                'correct_option': 'B',
            },
            {
                'text': 'Which writing style is best for a professional blog post?',
                'option_a': 'Academic and formal',
                'option_b': 'Casual and conversational yet informative',
                'option_c': 'Technical jargon only',
                'option_d': 'Poetic and metaphorical',
                'correct_option': 'B',
            },
            {
                'text': 'What is "white space" in content formatting?',
                'option_a': 'Text highlighted in white',
                'option_b': 'Empty space around text elements that improves readability',
                'option_c': 'A white background color',
                'option_d': 'Hidden text on a page',
                'correct_option': 'B',
            },
            {
                'text': 'Which of the following makes a headline effective?',
                'option_a': 'Using all capital letters',
                'option_b': 'Being vague and mysterious',
                'option_c': 'Being clear, specific, and promising a benefit',
                'option_d': 'Making it as long as possible',
                'correct_option': 'C',
            },
            {
                'text': 'What is the purpose of an editorial calendar?',
                'option_a': 'To track website visitors',
                'option_b': 'To schedule and plan content publication dates',
                'option_c': 'To calculate word count',
                'option_d': 'To manage email subscriptions',
                'correct_option': 'B',
            },
            {
                'text': 'What does "evergreen content" mean?',
                'option_a': 'Content about gardening and nature',
                'option_b': 'Content that remains relevant and useful over a long period',
                'option_c': 'Content written in green font',
                'option_d': 'Content published only in spring',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'Graphic Design Fundamentals',
        'domain': 'Graphic Design',
        'description': 'Test your knowledge of design principles, tools, and visual communication.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'What does RGB stand for in digital design?',
                'option_a': 'Red, Green, Blue',
                'option_b': 'Red, Gray, Black',
                'option_c': 'Real Graphic Blend',
                'option_d': 'Raster Grid Base',
                'correct_option': 'A',
            },
            {
                'text': 'Which file format supports transparency?',
                'option_a': 'JPEG',
                'option_b': 'PNG',
                'option_c': 'BMP',
                'option_d': 'TIFF',
                'correct_option': 'B',
            },
            {
                'text': 'What is the standard resolution for print design?',
                'option_a': '72 DPI',
                'option_b': '150 DPI',
                'option_c': '300 DPI',
                'option_d': '600 DPI',
                'correct_option': 'C',
            },
            {
                'text': 'Which principle of design refers to the arrangement of elements to create visual stability?',
                'option_a': 'Contrast',
                'option_b': 'Balance',
                'option_c': 'Repetition',
                'option_d': 'Proximity',
                'correct_option': 'B',
            },
            {
                'text': 'Which Adobe tool is primarily used for vector graphics?',
                'option_a': 'Photoshop',
                'option_b': 'Lightroom',
                'option_c': 'Illustrator',
                'option_d': 'Premiere Pro',
                'correct_option': 'C',
            },
            {
                'text': 'What is kerning in typography?',
                'option_a': 'The space between lines of text',
                'option_b': 'The space between individual characters',
                'option_c': 'The thickness of a font',
                'option_d': 'The size of a font',
                'correct_option': 'B',
            },
            {
                'text': 'Which color model is used for printing?',
                'option_a': 'RGB',
                'option_b': 'HSL',
                'option_c': 'CMYK',
                'option_d': 'HEX',
                'correct_option': 'C',
            },
            {
                'text': 'What is a mockup in graphic design?',
                'option_a': 'A finished product',
                'option_b': 'A realistic preview of how a design will look in context',
                'option_c': 'A wireframe without colors',
                'option_d': 'A font style',
                'correct_option': 'B',
            },
            {
                'text': 'Which design element is used to guide the viewer\'s eye through a composition?',
                'option_a': 'Texture',
                'option_b': 'Line',
                'option_c': 'Shape',
                'option_d': 'Visual hierarchy',
                'correct_option': 'D',
            },
            {
                'text': 'What is the difference between raster and vector graphics?',
                'option_a': 'Raster uses pixels; vector uses mathematical paths',
                'option_b': 'They are the same',
                'option_c': 'Vector uses pixels; raster uses paths',
                'option_d': 'Raster is for web only; vector is for print only',
                'correct_option': 'A',
            },
        ],
    },
    {
        'title': 'Freelancing Essentials',
        'domain': 'Freelancing',
        'description': 'Assess your understanding of freelancing platforms, client management, and business skills.',
        'time_limit': 10,
        'questions': [
            {
                'text': 'Which platform is most popular for freelance work worldwide?',
                'option_a': 'LinkedIn',
                'option_b': 'Upwork',
                'option_c': 'Facebook',
                'option_d': 'Instagram',
                'correct_option': 'B',
            },
            {
                'text': 'What should a freelancer include in their proposal?',
                'option_a': 'Only the price',
                'option_b': 'Understanding of the project, relevant skills, timeline, and price',
                'option_c': 'A copy of their resume only',
                'option_d': 'Just a greeting message',
                'correct_option': 'B',
            },
            {
                'text': 'What is a portfolio in freelancing?',
                'option_a': 'A financial investment document',
                'option_b': 'A collection of work samples showcasing your skills',
                'option_c': 'A client database',
                'option_d': 'A contract template',
                'correct_option': 'B',
            },
            {
                'text': 'What does "milestone payment" mean?',
                'option_a': 'Full payment upfront',
                'option_b': 'Payment divided into stages based on project progress',
                'option_c': 'Payment only at the end',
                'option_d': 'Bonus payment',
                'correct_option': 'B',
            },
            {
                'text': 'Which skill is most important for freelancer-client communication?',
                'option_a': 'Speed typing',
                'option_b': 'Clear and professional written communication',
                'option_c': 'Using emojis',
                'option_d': 'Speaking multiple languages',
                'correct_option': 'B',
            },
            {
                'text': 'What is the best practice when a client requests work outside the agreed scope?',
                'option_a': 'Do it for free to maintain the relationship',
                'option_b': 'Ignore the request',
                'option_c': 'Discuss the additional scope and negotiate revised terms',
                'option_d': 'Cancel the project',
                'correct_option': 'C',
            },
            {
                'text': 'Which is a DigiSkills.pk training program area?',
                'option_a': 'Cooking',
                'option_b': 'E-Commerce Management',
                'option_c': 'Fashion Design',
                'option_d': 'Architecture',
                'correct_option': 'B',
            },
            {
                'text': 'Why is niche specialization important in freelancing?',
                'option_a': 'It limits your options',
                'option_b': 'It helps you stand out and charge higher rates',
                'option_c': 'It is not important at all',
                'option_d': 'It makes you work less',
                'correct_option': 'B',
            },
            {
                'text': 'What is a Non-Disclosure Agreement (NDA)?',
                'option_a': 'A payment receipt',
                'option_b': 'A legal contract to protect confidential information',
                'option_c': 'A project proposal',
                'option_d': 'A freelancing platform policy',
                'correct_option': 'B',
            },
            {
                'text': 'What is the biggest advantage of freelancing?',
                'option_a': 'Guaranteed fixed salary',
                'option_b': 'Flexibility in choosing projects, clients, and schedule',
                'option_c': 'Company-provided equipment',
                'option_d': 'Paid vacation days',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'E-Commerce Knowledge Test',
        'domain': 'E-Commerce',
        'description': 'Test your understanding of online selling, platforms, and digital business.',
        'time_limit': 10,
        'questions': [
            {
                'text': 'What does B2C stand for in e-commerce?',
                'option_a': 'Business to Customer',
                'option_b': 'Business to Company',
                'option_c': 'Brand to Consumer',
                'option_d': 'Buy to Cart',
                'correct_option': 'A',
            },
            {
                'text': 'Which platform is commonly used for creating an online store?',
                'option_a': 'WordPress',
                'option_b': 'Shopify',
                'option_c': 'Slack',
                'option_d': 'Zoom',
                'correct_option': 'B',
            },
            {
                'text': 'What is dropshipping?',
                'option_a': 'Delivering products by drone',
                'option_b': 'Selling products without holding inventory; supplier ships directly',
                'option_c': 'A type of e-commerce website',
                'option_d': 'Discount selling strategy',
                'correct_option': 'B',
            },
            {
                'text': 'What is a "conversion rate" in e-commerce?',
                'option_a': 'The speed of the website',
                'option_b': 'Percentage of visitors who complete a desired action (purchase)',
                'option_c': 'The exchange rate of currency',
                'option_d': 'The number of products listed',
                'correct_option': 'B',
            },
            {
                'text': 'Which payment gateway is widely used in Pakistan for e-commerce?',
                'option_a': 'Stripe',
                'option_b': 'JazzCash / EasyPaisa',
                'option_c': 'Venmo',
                'option_d': 'Apple Pay',
                'correct_option': 'B',
            },
            {
                'text': 'What is SEO in the context of an e-commerce store?',
                'option_a': 'Selling Everything Online',
                'option_b': 'Search Engine Optimization to improve store visibility',
                'option_c': 'Standard E-commerce Operation',
                'option_d': 'Shipping and Export Office',
                'correct_option': 'B',
            },
            {
                'text': 'What does "SKU" stand for?',
                'option_a': 'Standard Keeping Unit',
                'option_b': 'Stock Keeping Unit',
                'option_c': 'Shop Key Utility',
                'option_d': 'Sales Knowledge Update',
                'correct_option': 'B',
            },
            {
                'text': 'What is the purpose of product photography in e-commerce?',
                'option_a': 'To make the website load slower',
                'option_b': 'To visually showcase products and increase sales',
                'option_c': 'To fill empty space on the page',
                'option_d': 'For social media only',
                'correct_option': 'B',
            },
            {
                'text': 'Which metric measures how often customers return to buy again?',
                'option_a': 'Bounce rate',
                'option_b': 'Customer retention rate',
                'option_c': 'Page views',
                'option_d': 'Click-through rate',
                'correct_option': 'B',
            },
            {
                'text': 'What is a shopping cart abandonment?',
                'option_a': 'When a store runs out of stock',
                'option_b': 'When a customer adds items to cart but leaves without purchasing',
                'option_c': 'When a cart is physically abandoned',
                'option_d': 'When a product is returned',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'Digital Marketing Fundamentals',
        'domain': 'Digital Marketing',
        'description': 'Test your knowledge of digital marketing channels, strategies, and analytics.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'What does PPC stand for in digital marketing?',
                'option_a': 'Pay Per Click',
                'option_b': 'Post Per Campaign',
                'option_c': 'Paid Promotion Channel',
                'option_d': 'Page Per Conversion',
                'correct_option': 'A',
            },
            {
                'text': 'Which platform is most used for B2B digital marketing?',
                'option_a': 'TikTok',
                'option_b': 'Snapchat',
                'option_c': 'LinkedIn',
                'option_d': 'Pinterest',
                'correct_option': 'C',
            },
            {
                'text': 'What is a "bounce rate" in Google Analytics?',
                'option_a': 'The percentage of emails that failed to deliver',
                'option_b': 'The percentage of visitors who leave after viewing only one page',
                'option_c': 'The speed at which a page loads',
                'option_d': 'The number of times an ad is shown',
                'correct_option': 'B',
            },
            {
                'text': 'What does CTR stand for?',
                'option_a': 'Customer Tracking Rate',
                'option_b': 'Content Traffic Report',
                'option_c': 'Click-Through Rate',
                'option_d': 'Campaign Target Reach',
                'correct_option': 'C',
            },
            {
                'text': 'What is a "lookalike audience" in Facebook Ads?',
                'option_a': 'People who look similar in photos',
                'option_b': 'An audience similar to your existing customers',
                'option_c': 'A remarketing list',
                'option_d': 'A list of influencers',
                'correct_option': 'B',
            },
            {
                'text': 'Which metric measures the cost to acquire one customer?',
                'option_a': 'ROI',
                'option_b': 'CPA (Cost Per Acquisition)',
                'option_c': 'CPM',
                'option_d': 'CPC',
                'correct_option': 'B',
            },
            {
                'text': 'What is email marketing automation?',
                'option_a': 'Sending emails manually to each subscriber',
                'option_b': 'Using software to send emails automatically based on triggers',
                'option_c': 'Buying email lists',
                'option_d': 'Sending emails from multiple accounts',
                'correct_option': 'B',
            },
            {
                'text': 'What is A/B testing in digital marketing?',
                'option_a': 'Testing two different products',
                'option_b': 'Comparing two versions of content to see which performs better',
                'option_c': 'Testing website speed',
                'option_d': 'Running ads on two platforms simultaneously',
                'correct_option': 'B',
            },
            {
                'text': 'Which factor most affects organic search ranking?',
                'option_a': 'Social media followers',
                'option_b': 'Quality backlinks and relevant content',
                'option_c': 'Website color scheme',
                'option_d': 'Domain registration date only',
                'correct_option': 'B',
            },
            {
                'text': 'What is influencer marketing?',
                'option_a': 'Marketing by company executives only',
                'option_b': 'Partnering with individuals who have an audience to promote products',
                'option_c': 'Advertising on TV',
                'option_d': 'Cold email campaigns',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'WordPress Website Development',
        'domain': 'WordPress',
        'description': 'Assess your knowledge of WordPress setup, plugins, themes, and website management.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'What type of software is WordPress?',
                'option_a': 'A programming language',
                'option_b': 'A Content Management System (CMS)',
                'option_c': 'A database engine',
                'option_d': 'An operating system',
                'correct_option': 'B',
            },
            {
                'text': 'Which of the following is a popular WordPress page builder plugin?',
                'option_a': 'WooCommerce',
                'option_b': 'Yoast SEO',
                'option_c': 'Elementor',
                'option_d': 'Wordfence',
                'correct_option': 'C',
            },
            {
                'text': 'What does a WordPress plugin do?',
                'option_a': 'Changes the visual design of a site',
                'option_b': 'Adds functionality to a WordPress website',
                'option_c': 'Hosts the website on a server',
                'option_d': 'Creates a database backup',
                'correct_option': 'B',
            },
            {
                'text': 'What is the purpose of the functions.php file in a WordPress theme?',
                'option_a': 'Store media files',
                'option_b': 'Add custom PHP functions and features to the theme',
                'option_c': 'Define CSS styles',
                'option_d': 'Configure the database',
                'correct_option': 'B',
            },
            {
                'text': 'Which WordPress plugin is most commonly used for SEO?',
                'option_a': 'WooCommerce',
                'option_b': 'Contact Form 7',
                'option_c': 'Yoast SEO',
                'option_d': 'Akismet',
                'correct_option': 'C',
            },
            {
                'text': 'What is a WordPress "child theme"?',
                'option_a': 'A smaller version of a theme',
                'option_b': 'A theme that inherits styles from a parent theme without modifying it',
                'option_c': 'A theme for children\'s websites',
                'option_d': 'A backup copy of a theme',
                'correct_option': 'B',
            },
            {
                'text': 'Which database does WordPress use by default?',
                'option_a': 'PostgreSQL',
                'option_b': 'SQLite',
                'option_c': 'MySQL / MariaDB',
                'option_d': 'MongoDB',
                'correct_option': 'C',
            },
            {
                'text': 'What is WooCommerce?',
                'option_a': 'A WordPress security plugin',
                'option_b': 'A WordPress plugin for building e-commerce stores',
                'option_c': 'A WordPress theme',
                'option_d': 'A website hosting service',
                'correct_option': 'B',
            },
            {
                'text': 'What does the wp-config.php file contain?',
                'option_a': 'All blog posts',
                'option_b': 'WordPress database credentials and configuration settings',
                'option_c': 'Plugin settings',
                'option_d': 'Theme CSS styles',
                'correct_option': 'B',
            },
            {
                'text': 'How do you add a custom menu in WordPress?',
                'option_a': 'Edit the database directly',
                'option_b': 'Go to Appearance → Menus in the WordPress admin',
                'option_c': 'Upload a menu.php file to the server',
                'option_d': 'Install a special hosting plan',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'Data Analytics Essentials',
        'domain': 'Data Analytics',
        'description': 'Test your knowledge of data analysis, visualization, and business intelligence tools.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'Which tool is most commonly used for data visualization?',
                'option_a': 'Microsoft Word',
                'option_b': 'Tableau',
                'option_c': 'Adobe Photoshop',
                'option_d': 'Notepad',
                'correct_option': 'B',
            },
            {
                'text': 'What does KPI stand for?',
                'option_a': 'Key Performance Indicator',
                'option_b': 'Known Process Integration',
                'option_c': 'Key Product Index',
                'option_d': 'Knowledge Pipeline Interface',
                'correct_option': 'A',
            },
            {
                'text': 'What is a pivot table used for?',
                'option_a': 'Creating presentations',
                'option_b': 'Summarizing and analyzing large datasets in spreadsheets',
                'option_c': 'Designing web pages',
                'option_d': 'Writing code',
                'correct_option': 'B',
            },
            {
                'text': 'Which language is most commonly used in data analytics?',
                'option_a': 'HTML',
                'option_b': 'Python',
                'option_c': 'CSS',
                'option_d': 'PHP',
                'correct_option': 'B',
            },
            {
                'text': 'What is a "dashboard" in business analytics?',
                'option_a': 'A car control panel',
                'option_b': 'A visual display of key metrics and data in one place',
                'option_c': 'A spreadsheet formula',
                'option_d': 'A database query',
                'correct_option': 'B',
            },
            {
                'text': 'What does ETL stand for in data processing?',
                'option_a': 'Extract, Transform, Load',
                'option_b': 'Edit, Test, Launch',
                'option_c': 'Export, Track, List',
                'option_d': 'Evaluate, Transfer, Log',
                'correct_option': 'A',
            },
            {
                'text': 'What is a "null value" in a dataset?',
                'option_a': 'A value of zero',
                'option_b': 'A missing or undefined value',
                'option_c': 'A negative number',
                'option_d': 'A text string',
                'correct_option': 'B',
            },
            {
                'text': 'Which chart type is best for showing trends over time?',
                'option_a': 'Pie chart',
                'option_b': 'Bar chart',
                'option_c': 'Line chart',
                'option_d': 'Scatter plot',
                'correct_option': 'C',
            },
            {
                'text': 'What is the purpose of data cleaning?',
                'option_a': 'Deleting all data from a database',
                'option_b': 'Removing errors, duplicates, and inconsistencies from a dataset',
                'option_c': 'Formatting text in reports',
                'option_d': 'Encrypting sensitive data',
                'correct_option': 'B',
            },
            {
                'text': 'What is SQL used for in data analytics?',
                'option_a': 'Creating graphics',
                'option_b': 'Querying and managing data in relational databases',
                'option_c': 'Building mobile apps',
                'option_d': 'Writing marketing copy',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'QuickBooks Accounting Skills',
        'domain': 'QuickBooks',
        'description': 'Assess your proficiency in QuickBooks for bookkeeping and financial management.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'What is QuickBooks primarily used for?',
                'option_a': 'Video editing',
                'option_b': 'Accounting and financial management for businesses',
                'option_c': 'Project management',
                'option_d': 'Social media marketing',
                'correct_option': 'B',
            },
            {
                'text': 'What is a "Chart of Accounts" in QuickBooks?',
                'option_a': 'A visual chart showing sales trends',
                'option_b': 'A list of all financial accounts used by a business',
                'option_c': 'A customer invoice template',
                'option_d': 'A payroll schedule',
                'correct_option': 'B',
            },
            {
                'text': 'What does "reconciliation" mean in QuickBooks?',
                'option_a': 'Sending invoices to clients',
                'option_b': 'Matching your QuickBooks records with your bank statement',
                'option_c': 'Creating a new account',
                'option_d': 'Running payroll',
                'correct_option': 'B',
            },
            {
                'text': 'Which report shows a company\'s financial position at a specific date?',
                'option_a': 'Profit & Loss Report',
                'option_b': 'Balance Sheet',
                'option_c': 'Cash Flow Statement',
                'option_d': 'Accounts Receivable Report',
                'correct_option': 'B',
            },
            {
                'text': 'What is an "accounts receivable" in QuickBooks?',
                'option_a': 'Money the business owes to suppliers',
                'option_b': 'Money owed to the business by customers',
                'option_c': 'Employee salaries',
                'option_d': 'Bank loan balance',
                'correct_option': 'B',
            },
            {
                'text': 'What is the purpose of a "journal entry" in QuickBooks?',
                'option_a': 'Writing daily business notes',
                'option_b': 'Recording a financial transaction manually',
                'option_c': 'Creating a budget forecast',
                'option_d': 'Generating tax forms',
                'correct_option': 'B',
            },
            {
                'text': 'What does "double-entry bookkeeping" mean?',
                'option_a': 'Entering data twice to avoid errors',
                'option_b': 'Every transaction affects at least two accounts (debit and credit)',
                'option_c': 'Using two different software programs',
                'option_d': 'Having two accountants review records',
                'correct_option': 'B',
            },
            {
                'text': 'Which QuickBooks feature allows tracking money owed to vendors?',
                'option_a': 'Accounts Receivable',
                'option_b': 'Accounts Payable',
                'option_c': 'Payroll',
                'option_d': 'Inventory',
                'correct_option': 'B',
            },
            {
                'text': 'What is the Profit & Loss report used for?',
                'option_a': 'Listing all bank transactions',
                'option_b': 'Showing revenues, expenses, and net profit over a period',
                'option_c': 'Tracking employee hours',
                'option_d': 'Managing inventory counts',
                'correct_option': 'B',
            },
            {
                'text': 'What is "depreciation" in accounting?',
                'option_a': 'An increase in asset value over time',
                'option_b': 'The gradual reduction in value of an asset over time',
                'option_c': 'A tax refund',
                'option_d': 'A type of business loan',
                'correct_option': 'B',
            },
        ],
    },
    {
        'title': 'AutoCAD Technical Drawing',
        'domain': 'AutoCAD',
        'description': 'Test your knowledge of AutoCAD tools, commands, and technical drawing concepts.',
        'time_limit': 12,
        'questions': [
            {
                'text': 'What is AutoCAD primarily used for?',
                'option_a': 'Video editing',
                'option_b': '2D drafting and 3D design of technical drawings',
                'option_c': 'Accounting',
                'option_d': 'Web development',
                'correct_option': 'B',
            },
            {
                'text': 'What does the AutoCAD command "LINE" do?',
                'option_a': 'Creates a curved arc',
                'option_b': 'Draws a straight line between two points',
                'option_c': 'Inserts a text block',
                'option_d': 'Copies an object',
                'correct_option': 'B',
            },
            {
                'text': 'What is a "layer" in AutoCAD?',
                'option_a': 'A type of 3D solid',
                'option_b': 'An organizational tool to group drawing elements',
                'option_c': 'A printing setting',
                'option_d': 'A file format',
                'correct_option': 'B',
            },
            {
                'text': 'What does the TRIM command do in AutoCAD?',
                'option_a': 'Copies an object to a new location',
                'option_b': 'Removes portions of objects that extend beyond a boundary',
                'option_c': 'Rotates an object',
                'option_d': 'Changes the color of an object',
                'correct_option': 'B',
            },
            {
                'text': 'What is the file extension for an AutoCAD drawing file?',
                'option_a': '.pdf',
                'option_b': '.dwg',
                'option_c': '.psd',
                'option_d': '.ai',
                'correct_option': 'B',
            },
            {
                'text': 'What does OSNAP stand for in AutoCAD?',
                'option_a': 'Object Snap',
                'option_b': 'Original Shape Navigation and Print',
                'option_c': 'Outline Shape and Path',
                'option_d': 'Object Scale and Position',
                'correct_option': 'A',
            },
            {
                'text': 'Which AutoCAD command is used to create a copy of an object at a specific distance?',
                'option_a': 'MOVE',
                'option_b': 'MIRROR',
                'option_c': 'OFFSET',
                'option_d': 'SCALE',
                'correct_option': 'C',
            },
            {
                'text': 'What is the purpose of a "viewport" in AutoCAD paper space?',
                'option_a': 'To view 3D models in virtual reality',
                'option_b': 'To display model space views within a layout sheet for printing',
                'option_c': 'To zoom into a drawing',
                'option_d': 'To save a screenshot',
                'correct_option': 'B',
            },
            {
                'text': 'What does the MIRROR command do in AutoCAD?',
                'option_a': 'Duplicates an object and flips it across an axis',
                'option_b': 'Creates a transparent copy',
                'option_c': 'Rotates an object 180 degrees in place',
                'option_d': 'Scales an object by half',
                'correct_option': 'A',
            },
            {
                'text': 'What unit is commonly used in architectural AutoCAD drawings?',
                'option_a': 'Pixels',
                'option_b': 'Points',
                'option_c': 'Millimetres or feet/inches',
                'option_d': 'Centimetres only',
                'correct_option': 'C',
            },
        ],
    },
]


class Command(BaseCommand):
    help = 'Seeds the database with sample assessments and MCQ questions.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear', action='store_true',
            help='Remove existing assessments and questions before seeding.',
        )

    def handle(self, *args, **options):
        if options['clear']:
            count = Assessment.objects.count()
            Assessment.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Cleared {count} existing assessments.'))

        created_assessments = 0
        created_questions = 0

        for data in SEED_DATA:
            questions_data = data.pop('questions')

            assessment, created = Assessment.objects.get_or_create(
                title=data['title'],
                defaults=data,
            )
            if created:
                created_assessments += 1
                for idx, q in enumerate(questions_data, start=1):
                    Question.objects.create(
                        assessment=assessment,
                        order=idx,
                        **q,
                    )
                    created_questions += 1
                self.stdout.write(f'  ✓ {assessment.title} ({len(questions_data)} questions)')
            else:
                self.stdout.write(f'  – {assessment.title} already exists, skipping.')

            # Restore questions_data for potential re-run
            data['questions'] = questions_data

        self.stdout.write(self.style.SUCCESS(
            f'\nSeeding complete: {created_assessments} assessments, {created_questions} questions created.'
        ))
